{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"public candlestick_data\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.754.0 (24.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "1b1c4150-386d-4174-9839-4cd429a5691c",
        "fromColumn": "time_custom",
        "fromTable": "public candlestick_data",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3989a57c-6214-4a9b-901a-3bec2913a1f2"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "public candlestick_data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2cb03a9d-6a36-44bc-a8fc-b69b53a87a51",
            "sourceColumn": "id",
            "summarizeBy": "sum"
          },
          {
            "name": "time_custom",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"public candlestick_data\",\"TableItemName\":\"time_custom (bins)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"public candlestick_data\",\"TableItemName\":\"day\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"public candlestick_data\",\"TableItemName\":\"day_time\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "fefad1dd-9942-421f-938c-6abc795ebcda",
            "sourceColumn": "time_custom",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3989a57c-6214-4a9b-901a-3bec2913a1f2"
                },
                "isDefault": true,
                "relationship": "1b1c4150-386d-4174-9839-4cd429a5691c"
              }
            ]
          },
          {
            "name": "open_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b04c55a6-5fa0-4eb7-9038-9c340fa37752",
            "sourceColumn": "open_price",
            "summarizeBy": "sum"
          },
          {
            "name": "close_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a1f6d980-43f6-4624-b8ba-496b37491309",
            "sourceColumn": "close_price",
            "summarizeBy": "sum"
          },
          {
            "name": "high_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2b3edfff-27af-4fbb-b51f-bbee4802fcaf",
            "sourceColumn": "high_price",
            "summarizeBy": "sum"
          },
          {
            "name": "low_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bb64b7ad-f1c1-459a-bc98-47ab92a20239",
            "sourceColumn": "low_price",
            "summarizeBy": "sum"
          },
          {
            "name": "volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "15bdea2f-ca27-4846-b647-dc6a294f9e6a",
            "sourceColumn": "volume",
            "summarizeBy": "sum"
          },
          {
            "name": "symbol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2248dcbe-7d52-42d4-8ae2-e57072c1ad85",
            "sourceColumn": "symbol",
            "summarizeBy": "none"
          },
          {
            "name": "time_custom (bins)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"p\",\"Entity\":\"public candlestick_data\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"time_custom\"}}],\"BinItem\":{\"Expression\":{\"Floor\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"time_custom\"}},\"Size\":30.0,\"TimeUnit\":6}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "IF(",
              "\tISBLANK('public candlestick_data'[time_custom]),",
              "\tBLANK(),",
              "\t(INT(('public candlestick_data'[time_custom] * 1440) / 30) * 30) / 1440",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "binningMetadata": {
                    "binSize": {
                      "unit": 10,
                      "value": 30.0
                    }
                  },
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "public candlestick_data"
                          }
                        },
                        "Property": "time_custom"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "formatString": "General Date",
            "lineageTag": "91fdd4d0-c61e-4983-85d2-a00e5f0ed74b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "day",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"p\",\"Entity\":\"public candlestick_data\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"time_custom\"}}],\"BinItem\":{\"Expression\":{\"Floor\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"time_custom\"}},\"Size\":1.0,\"TimeUnit\":0}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "IF(",
              "\tISBLANK('public candlestick_data'[time_custom]),",
              "\tBLANK(),",
              "\t1 + INT(INT('public candlestick_data'[time_custom]) - 1)",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "binningMetadata": {
                    "binSize": {
                      "unit": 8,
                      "value": 1.0
                    }
                  },
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "public candlestick_data"
                          }
                        },
                        "Property": "time_custom"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "formatString": "Short Date",
            "lineageTag": "c69bdb98-a8c3-4ed2-aa74-de794581e020",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "day_time",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"p\",\"Entity\":\"public candlestick_data\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"time_custom\"}}],\"BinItem\":{\"Expression\":{\"Floor\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"time_custom\"}},\"Size\":3.0,\"TimeUnit\":0}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "IF(",
              "\tISBLANK('public candlestick_data'[time_custom]),",
              "\tBLANK(),",
              "\t1 + (INT((INT('public candlestick_data'[time_custom]) - 1) / 3) * 3)",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "binningMetadata": {
                    "binSize": {
                      "unit": 8,
                      "value": 3.0
                    }
                  },
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "public candlestick_data"
                          }
                        },
                        "Property": "time_custom"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "formatString": "Short Date",
            "lineageTag": "d55f21fa-075f-4c20-84f9-030e6c752fba",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "71d1581a-0b49-495f-9ee1-88521e0f7ca5",
        "partitions": [
          {
            "name": "public candlestick_data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"localhost:5433\", \"crypto\"),",
                "    public_candlestick_data = Source{[Schema=\"public\",Item=\"candlestick_data\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(public_candlestick_data,{{\"time\", \"time_custom\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_918ec1c5-6856-4f6a-9828-12f98ad585dc",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5ff9fcdd-e9c5-4855-ad19-cb0bda08cb0b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ff1551ba-0b51-4263-8c89-85e48b38c639",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a83ac848-6d5c-4996-ad2d-b4bf65771264",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "092fd8ec-6e28-461b-9339-d1fd25e62ddc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "09cbca2b-04f4-413a-93e1-8a4a6335798b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "08ac24f4-0e40-4ade-8216-b55591a931e3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "117b504d-f33c-4f38-abaf-3422d69eb1da",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "335a4abc-b0d8-4ec3-8abf-21e466f93e16",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "023c557e-e681-4526-b414-498b03edfe2c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5b5ab797-f113-4e00-b2f7-1c38b3c6ff45",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f506eb4c-7e71-4552-ab39-95e41f9f3b95",
                "ordinal": 3
              }
            ],
            "lineageTag": "c3554d17-0143-4c42-aa51-db2399b72220"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "3be3bd59-c7ac-4fbd-acdc-2d671b52c474",
        "partitions": [
          {
            "name": "DateTableTemplate_918ec1c5-6856-4f6a-9828-12f98ad585dc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_3989a57c-6214-4a9b-901a-3bec2913a1f2",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a051c111-eee3-4b64-9d9c-899e9d619cf0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e82bc474-b0f4-4418-8712-cca10d6d3fa5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d3543a3f-a308-4176-8013-b11835a5eb9f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8cda3614-aead-4c35-9c95-5d4fd605f7f2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "36772570-741f-428a-987e-89ac13672aca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f705d221-4496-41c9-ae1a-3da27202624f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "795591e3-fd2f-4950-9df6-21759b71f0c8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1be4f27e-2902-41f9-a216-af689fbe1c4a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "48df52d1-d8de-403d-a01a-cb3bae0befa7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a3659117-89c3-4328-ab80-0231eea2cc35",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d9cb031b-6813-4b27-b508-4fa635e10453",
                "ordinal": 3
              }
            ],
            "lineageTag": "3df653ef-ca0f-41d5-9492-d1fdeffc5423"
          }
        ],
        "isHidden": true,
        "lineageTag": "b0dc20b0-15fc-41f5-bbf6-5b1c73879fb3",
        "partitions": [
          {
            "name": "LocalDateTable_3989a57c-6214-4a9b-901a-3bec2913a1f2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('public candlestick_data'[time_custom])), 1, 1), Date(Year(MAX('public candlestick_data'[time_custom])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}